# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: servidor.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eservidor.proto\x12\x08servidor\"5\n\x07\x43liente\x12\x0c\n\x04nome\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\r\n\x05senha\x18\x03 \x01(\t\"\x9a\x01\n\x07Voucher\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0e\n\x06titulo\x18\x02 \x01(\t\x12\x11\n\tdescricao\x18\x03 \x01(\t\x12\x0c\n\x04gato\x18\x04 \x01(\t\x12\r\n\x05local\x18\x05 \x01(\t\x12\x0e\n\x06lanche\x18\x06 \x01(\t\x12\x0f\n\x07\x64uracao\x18\x07 \x01(\x05\x12\x0e\n\x06imagem\x18\x08 \x01(\t\x12\x12\n\ntitular_id\x18\t \x01(\x05\"(\n\x08Vouchers\x12\x1c\n\x01v\x18\x01 \x03(\x0b\x32\x11.servidor.Voucher\"V\n\nComp_Troca\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x1d\n\x02v1\x18\x02 \x01(\x0b\x32\x11.servidor.Voucher\x12\x1d\n\x02v2\x18\x03 \x01(\x0b\x32\x11.servidor.Voucher\")\n\x06Trocas\x12\x1f\n\x01t\x18\x01 \x03(\x0b\x32\x14.servidor.Comp_Troca\"!\n\x05Troca\x12\x0b\n\x03id1\x18\x01 \x01(\x05\x12\x0b\n\x03id2\x18\x02 \x01(\x05\"\x1b\n\x08Resposta\x12\x0f\n\x07message\x18\x01 \x01(\x05\"\x10\n\x02ID\x12\n\n\x02id\x18\x01 \x01(\x05\x32\x86\x01\n\ropcoesCliente\x12;\n\x10\x63\x61\x64\x61strarCliente\x12\x11.servidor.Cliente\x1a\x12.servidor.Resposta\"\x00\x12\x38\n\rchecarCliente\x12\x11.servidor.Cliente\x1a\x12.servidor.Resposta\"\x00\x32\xc7\x01\n\ropcoesVoucher\x12;\n\x10\x63\x61\x64\x61strarVoucher\x12\x11.servidor.Voucher\x1a\x12.servidor.Resposta\"\x00\x12?\n\x19\x61presentarVouchersUsuario\x12\x0c.servidor.ID\x1a\x12.servidor.Vouchers\"\x00\x12\x38\n\x12\x61presentarVouchers\x12\x0c.servidor.ID\x1a\x12.servidor.Vouchers\"\x00\x32\xe9\x01\n\x0bopcoesTroca\x12\x37\n\x10\x61presentarTrocas\x12\x0f.servidor.Troca\x1a\x10.servidor.Trocas\"\x00\x12\x34\n\x0bproporTroca\x12\x0f.servidor.Troca\x1a\x12.servidor.Resposta\"\x00\x12\x36\n\rrealizarTroca\x12\x0f.servidor.Troca\x1a\x12.servidor.Resposta\"\x00\x12\x33\n\nnegarTroca\x12\x0f.servidor.Troca\x1a\x12.servidor.Resposta\"\x00\x62\x06proto3')



_CLIENTE = DESCRIPTOR.message_types_by_name['Cliente']
_VOUCHER = DESCRIPTOR.message_types_by_name['Voucher']
_VOUCHERS = DESCRIPTOR.message_types_by_name['Vouchers']
_COMP_TROCA = DESCRIPTOR.message_types_by_name['Comp_Troca']
_TROCAS = DESCRIPTOR.message_types_by_name['Trocas']
_TROCA = DESCRIPTOR.message_types_by_name['Troca']
_RESPOSTA = DESCRIPTOR.message_types_by_name['Resposta']
_ID = DESCRIPTOR.message_types_by_name['ID']
Cliente = _reflection.GeneratedProtocolMessageType('Cliente', (_message.Message,), {
  'DESCRIPTOR' : _CLIENTE,
  '__module__' : 'servidor_pb2'
  # @@protoc_insertion_point(class_scope:servidor.Cliente)
  })
_sym_db.RegisterMessage(Cliente)

Voucher = _reflection.GeneratedProtocolMessageType('Voucher', (_message.Message,), {
  'DESCRIPTOR' : _VOUCHER,
  '__module__' : 'servidor_pb2'
  # @@protoc_insertion_point(class_scope:servidor.Voucher)
  })
_sym_db.RegisterMessage(Voucher)

Vouchers = _reflection.GeneratedProtocolMessageType('Vouchers', (_message.Message,), {
  'DESCRIPTOR' : _VOUCHERS,
  '__module__' : 'servidor_pb2'
  # @@protoc_insertion_point(class_scope:servidor.Vouchers)
  })
_sym_db.RegisterMessage(Vouchers)

Comp_Troca = _reflection.GeneratedProtocolMessageType('Comp_Troca', (_message.Message,), {
  'DESCRIPTOR' : _COMP_TROCA,
  '__module__' : 'servidor_pb2'
  # @@protoc_insertion_point(class_scope:servidor.Comp_Troca)
  })
_sym_db.RegisterMessage(Comp_Troca)

Trocas = _reflection.GeneratedProtocolMessageType('Trocas', (_message.Message,), {
  'DESCRIPTOR' : _TROCAS,
  '__module__' : 'servidor_pb2'
  # @@protoc_insertion_point(class_scope:servidor.Trocas)
  })
_sym_db.RegisterMessage(Trocas)

Troca = _reflection.GeneratedProtocolMessageType('Troca', (_message.Message,), {
  'DESCRIPTOR' : _TROCA,
  '__module__' : 'servidor_pb2'
  # @@protoc_insertion_point(class_scope:servidor.Troca)
  })
_sym_db.RegisterMessage(Troca)

Resposta = _reflection.GeneratedProtocolMessageType('Resposta', (_message.Message,), {
  'DESCRIPTOR' : _RESPOSTA,
  '__module__' : 'servidor_pb2'
  # @@protoc_insertion_point(class_scope:servidor.Resposta)
  })
_sym_db.RegisterMessage(Resposta)

ID = _reflection.GeneratedProtocolMessageType('ID', (_message.Message,), {
  'DESCRIPTOR' : _ID,
  '__module__' : 'servidor_pb2'
  # @@protoc_insertion_point(class_scope:servidor.ID)
  })
_sym_db.RegisterMessage(ID)

_OPCOESCLIENTE = DESCRIPTOR.services_by_name['opcoesCliente']
_OPCOESVOUCHER = DESCRIPTOR.services_by_name['opcoesVoucher']
_OPCOESTROCA = DESCRIPTOR.services_by_name['opcoesTroca']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CLIENTE._serialized_start=28
  _CLIENTE._serialized_end=81
  _VOUCHER._serialized_start=84
  _VOUCHER._serialized_end=238
  _VOUCHERS._serialized_start=240
  _VOUCHERS._serialized_end=280
  _COMP_TROCA._serialized_start=282
  _COMP_TROCA._serialized_end=368
  _TROCAS._serialized_start=370
  _TROCAS._serialized_end=411
  _TROCA._serialized_start=413
  _TROCA._serialized_end=446
  _RESPOSTA._serialized_start=448
  _RESPOSTA._serialized_end=475
  _ID._serialized_start=477
  _ID._serialized_end=493
  _OPCOESCLIENTE._serialized_start=496
  _OPCOESCLIENTE._serialized_end=630
  _OPCOESVOUCHER._serialized_start=633
  _OPCOESVOUCHER._serialized_end=832
  _OPCOESTROCA._serialized_start=835
  _OPCOESTROCA._serialized_end=1068
# @@protoc_insertion_point(module_scope)
